### ISSUE TITLE
Landing-Page

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#1]
User story template 

## Value Preposition

**As a User** 
**I need** a Landing Page
**to be able to** get an overview and have three different options to choose from 

## Description

<img src="https://user-images.githubusercontent.com/98495821/161385442-2bf9a1c7-ca66-4d5f-8c6b-b7b83ce585b9.svg" alt="Picture of Landing Page" width="300">

## Acceptance Criteria

- [x] Button must be clickable 
- [x] on click new Layout is shown

## Tasks

(for developers team)

- [x] create Branch Landing-Page
- [x] implement Contact Form, Categories and Random Button 
- [x] test on different Browser
