### ISSUE TITLE
show random restaurant

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#1]
## Value Preposition

**As a User** 
**I need** a tool which shows a random restaurant (and location ) nearby
**to be able to** skip a conversation and save time.

## Description

![capstoneproject-2022-03-20-teil1](https://user-images.githubusercontent.com/98495821/159690799-d228924c-112c-49c0-8740-a9e73310f2e8.svg)
![capstoneproject-2022-03-20-teil2Kopie](https://user-images.githubusercontent.com/98495821/159690795-6a4642f2-696f-4444-8db0-5252a1d088c7.svg)

## Acceptance Criteria

- [ ] Button must be clicked to show a random restaurant nearby through Google places API 
- [ ] Restaurant will be  displayed in a card with a picture - Restaurantname and opening times

## Tasks

(for developers team)

- [ ] create new branch fetch google places api - restaurant and save as separate data to avoid multiple fetch
- [ ] create list of restaurant and save as separate data to avoid multiple fetch
- [ ] create a fetch function and implement to the button
- [ ] update styles if necessary
- [ ] Test on mobile device / different Browser
