### ISSUE TITLE
Backend Database

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#10]
## Value Preposition

**As a User** 
**I need** a Database
**to be able to** get results(Restaurant information), which will be displayed  in the App.

## Description

The restaurant data will be stored in a database (Mongodb). The user will get the information by requesting it thorugh the app.

## Acceptance Criteria

- [ ] by clicking the Random or a Category button data will be displayed
- [ ] by submitting Contact form - email is send to Appowner(developer) emailaddress
- [ ] vulnerabel data will be stored in db

## Tasks

(for developers team)

- [ ] create new branch Database
- [ ]  install and setup MongoDB and mongoose in the project
- [ ] build function to GET data
