### ISSUE TITLE
go back button

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#13]
## Value Preposition

**As a User** 
**I need** the possibility to go back (a page) 
**to be able to** return to the page where I was before

## Description

<img src="https://user-images.githubusercontent.com/98495821/161386989-28aea30a-9e05-4672-88a2-2faef7d3eccb.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] go back button should only be displayed when it is possible to do so

## Tasks

(for developers team)

- [x] create new branch GoBackButton
- [x] implement functionality to Button component
- [x] style differntly than the other buttons ( maybe "arrow reverse" )
