### ISSUE TITLE
Add Map to Card

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#17]
## Value Preposition

**As a User** 
**I need** to see where the shown/suggested Restaurant is located
**to be able to** navigate  to the Restaurant

## Description

<img src="https://user-images.githubusercontent.com/98495821/162569124-b18b826a-6015-49ce-8d6c-40fa0d777487.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] Map should show the restaurant location with a pin
- [x] on Click  the Map should open Google Maps with the target(restaurant)

## Tasks

(for developers team)

- [x] create new branch Map
- [x] implement maps 
- [x] store api key safely
- [x] build map component
- [x] implement map in Restaurantcard
