### ISSUE TITLE
Light Mode

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#18]
## Value Preposition

**As a User** 
**I need** a dark mode 
**to be able to** to choose which layout suits me

## Description

<img src="https://user-images.githubusercontent.com/98495821/162572945-8f3f86c0-cb99-4d2d-9775-b0fc79a6c96a.svg" alt="Picture of User Story 1" width="300">
<img src="https://user-images.githubusercontent.com/98495821/162572963-03f0268e-8cac-4599-bfed-2d08d8dbdf49.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [ ] there should be a button on the top 
- [ ] button should have a toggle functionality
- [ ] on click the shown layout changes

## Tasks

(for developers team)

- [ ] create branch Darkmode
- [ ] create a button with toggle functionality
- [ ] write styled components for Darkmode
- [ ] storybook specs
- [ ] test on different Browsers
