### ISSUE TITLE
Tag Slidebar

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#19]
## Value Preposition

**As a User** 
**I need** Slidebar on the Categories Page
**to be able to** have a better overview of the Buttons

## Description

<img src="https://user-images.githubusercontent.com/98495821/162620562-741a0489-fbbd-4a7c-a389-0bb36817a652.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] Slidebar should show few tags/buttons
- [x] Slidebar should be slideable (horizontal) and show the following buttons
- [x] only 1 button vertically 

## Tasks

(for developers team)

- [x] create Branch Slidebar
- [x] add styling to fit buttons in
