### ISSUE TITLE
Categories-Page

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#2]
User story template 

## Value Preposition

**As a User** 
**I need**  different Categories
**to be able to** choose manually if random suggestion is no option

## Description

<img src="https://user-images.githubusercontent.com/98495821/160276548-5a63d2f8-3ab6-4a1e-b010-69d4eceb4861.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] Categories must be clickable
- [x] on click  on a Category a new list of Restaurant is displayed

## Tasks

(for developers team)

- [x] create new Branch Categories Page
- [x] build new arrays from Restaurant array(json)
- [x] add functionality to Categories Button
- [ ] build specs and stories
- [x] test on different browser
