### ISSUE TITLE
not rdy

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#2]
User story template 

## Value Preposition

**As a User** 
**I need** a input field to type in my current Adress
**to be able to** see actual restaurants in my area

## Description

![capstoneproject-2022-03-20-gps](https://user-images.githubusercontent.com/98495821/159749743-e30d5208-e135-479a-8a72-53ed056679a7.svg)

## Acceptance Criteria

- [ ] 
- [ ] e.g. All Inputs are required, show warning if empty.
- [ ] ...

## Tasks

(for developers team)

- [ ] list the tasks that need to be performed within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] ...
