### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#23]
## Value Preposition

**As a User** 
**I need** a Navigation
**to be able to** navigate properly through the app

## Description

Navigation with 5 Buttons( for each Page ) on bottom of the Page

## Acceptance Criteria

- [ ] Navigation should be on the Bottom
- [ ] Styling should fit the whole Theme of the App
- [ ] additional the App Name should navigate back to the Homepage

## Tasks

(for developers team)

- [ ] create branch Navigation
- [ ] build Navigation component
- [ ] specs and stories
- [ ] implement Navigation Component on each page
