### ISSUE TITLE
RandomButton

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#3]
## Value Preposition

**As a User**
**I need** to click a Button
**to be able to** get a Random Restaurant Card as suggestion

## Description

<img src="https://user-images.githubusercontent.com/98495821/160276421-d17d7068-3eb6-42b6-b74b-8f1f7189c381.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] Button must be clicked to show a random restaurant in Hamburg 
- [x] by clicking again a new Restaurant should be displayed

## Tasks

(for developers team)

- [x] create RandomButton branch
- [x] build button component
- [x] build storybook and specs for each component
- [x] create a  temporary JSON file wit Restaurant data
- [x] display information in card by clicking button 
- [x] update styles if necessary
- [x] test on different Browsers
