### ISSUE TITLE
Restaurant-Form

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#4]
User story template 

## Value Preposition

**As a User** 'Restaurantowner'
**I need** a Form  to type in my Restaurant Name and Adress
**to be able to** send a request to be listed in the App
## Description

<img src="https://user-images.githubusercontent.com/98495821/160275623-fe8e6b6b-dd60-43b0-922f-eeb13d0845da.svg" alt="Picture of User Story 1" width="300">

## Acceptance Criteria

- [x] Form needs Name, Adress and Contact(including phone Number) Input.
- [x] Every single Input is required
- [x] on Submit a request ist sent via mail

## Tasks

(for developers team)
- [x] create FormRequest branch
- [x] Build RequestForm component with 3 inputs and a button
- [x] Specs and Stories for Form component
- [x] Add functionality to Form - and check if request is sent
- [x] display success message
- [x] test in diffrent browsers

**Comment by PReichetanz** [comment]
Questions:
- Wouldn't it be good to add your phone number as well?
- What happens after submitting? What is displayed to the user?
- What happens if one of the required fields are left blank?

**Comment by ZeshanShahid79** [comment]
Thank you
