### ISSUE TITLE
Landing-Page

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#5]
User story template 

## Value Preposition

**As a User** 
**I need** a Landing Page
**to be able to** get an overview and have two different optionalities to choose from 

## Description

<img src="https://user-images.githubusercontent.com/98495821/160276844-8541120c-4630-48e6-8c88-251989a17584.svg" alt="Picture of Landing Page" width="300">

## Acceptance Criteria

- [ ] Button must be clickable 
- [ ] on click new Layout is shown

## Tasks

(for developers team)

- [ ] create Branch Landing-Page
- [ ] implement former Categories and Random Button 
- [ ] add Logo
- [ ] test on different Browser
