### ISSUE TITLE
Restaurant Card

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/capstone-project#5]
## Value Preposition

**As a User** 
**I need** to see a random restaurant  nearby
**to be able to** choose more efficiently

## Description

<img src="https://user-images.githubusercontent.com/98495821/160276345-b320444b-2493-4309-ae6d-5f8a0eabbd33.svg" alt="Picture of User Story 1" width="300"/>

## Acceptance Criteria

- [x] Restaurant will be  displayed in a card with - Restaurantname, address and details
- [x] Reloading the page will show different Restaurant

## Tasks

- [x] create new branch RestaurantCard 
- [x] build card components
- [x] build storybook and specs for each component
- [x] Test on mobile device / different Browser
